cmd_/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/list.o := arm-rdk-linux-gnueabi-gcc -Wp,-MD,/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/.list.o.d  -nostdinc -isystem /ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/sysroots/x86_64-linux/usr/lib/cortexa7t2hf-vfp-vfpv4-neon-rdk-linux-gnueabi/gcc/arm-rdk-linux-gnueabi/4.8.3/include -I./arch/arm/include -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-bcm2709/include -I/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one -I/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/single -I/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/include -I/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/linux/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(list)"  -D"KBUILD_MODNAME=KBUILD_STR(linux_one)" -c -o /ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/.tmp_list.o /ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/list.c

source_/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/list.o := /ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/list.c

deps_/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/list.o := \

/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/list.o: $(deps_/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/list.o)

$(deps_/ssd/pritam/raspi3KUL/build-raspberrypi3/tmp/work/raspberrypi3-rdk-linux-gnueabi/linux-fusion/9.0.3-r0/linux-fusion-9.0.3/one/list.o):
